version: "3"

services:
  nodbesd:
    image: besio/bes:v1.0.1
    command: /opt/besio/bin/nodbesd.sh --data-dir /opt/besio/bin/data-dir -e
    hostname: nodbesd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodbes-data-volume:/opt/besio/bin/data-dir

  kbesd:
    image: besio/bes:v1.0.1
    command: /opt/besio/bin/kbesd --wallet-dir /opt/besio/bin/data-dir --http-server-address=127.0.0.1:8900
    hostname: kbesd
    links:
      - nodbesd
    volumes:
      - kbesd-data-volume:/opt/besio/bin/data-dir

volumes:
 nodbes-data-volume:
   external: true
 kbesd-data-volume:
   external: true
