version: "3"

services:
  builder:
    build:
      context: builder
    image: besio/builder

  nodbesd:
    build:
      context: .
    image: besio/bes
    command: /opt/besio/bin/nodbesd.sh --data-dir /opt/besio/bin/data-dir -e --http-alias=nodbesd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodbesd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodbes-data-volume:/opt/besio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  kbesd:
    image: besio/bes
    command: /opt/besio/bin/kbesd --wallet-dir /opt/besio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=kbesd:8900 --http-alias=localhost:8900
    hostname: kbesd
    links:
      - nodbesd
    volumes:
      - kbesd-data-volume:/opt/besio/bin/data-dir
    stop_grace_period: 10m

volumes:
  nodbes-data-volume:
    external: true
  kbesd-data-volume:
    external: true
